version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: longqb-devops-project3-repository
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Starting to build at `date`
      - echo Building the Docker image ...
      - echo Please wait ...
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG ./analytics/.
      - echo docker images
      - docker images
  post_build:
    commands:
      - echo Successfully build at `date`
      - echo Pushing the Docker image to AWS ECR ...
      - echo Please wait ...
      - docker tag $IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
